export const SaleNftType = {
  PUT_ON_SALE: 0,
  MAKE_OFFER: 1,
  CANCEL_SALE_NFT: 2,
  EDIT_ORDER: 7,
  BUY_NFT: 3,
  ACCEPT_NFT: 4,
  UPDATE_NFT: 5,
  BURN_NFT: 6,
  CANCEL_MAKE_OFFER: 9,
  RECLAIM_MAKE_OFFER: 10,
  MINT_NFT: 15,
  SALE_TRANSFER_NFT: 89,

  CANCEL_AUCTION: 18,
  PUT_AUCTION: 19,
  BID_NFT: 20,
  BID_EDITED: 21,
  CANCEL_BID_NFT: 22,
  RECLAIM_BID_NFT: 24,
  WINNER_BID_NFT: 23,
  ACCEPT_BID_NFT: 25,
  RECLAIM_NFT: 26,

  CHANGE_OWNER_NFT: 28,
};

export const SaleNftStatus = {
  NEW: 0,
  SUCCESS: 1,
  FAIL: -1,
  NOT_COUNT: 2,
  MAKE_OFFER_EXPIRED: 4,
};
